# Generated by Django 5.1.7 on 2025-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
