# Generated by Django 5.1.7 on 2025-05-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0007_cliente_tarea_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='areaOperativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombreLogo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
